// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=js"
// @generated from file bible/v1/version.proto (package bible.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_protoc_gen_openapiv2_options_annotations } from "../../protoc-gen-openapiv2/options/annotations_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bible/v1/version.proto.
 */
export const file_bible_v1_version: GenFile = /*@__PURE__*/
  fileDesc("ChZiaWJsZS92MS92ZXJzaW9uLnByb3RvEghiaWJsZS52MSKpAgoHVmVyc2lvbhIKCgJpZBgBIAEoCRIMCgRjb2RlGAIgASgJEgwKBG5hbWUYAyABKAkSEAoIbGFuZ3VhZ2UYBCABKAkSDgoGc291cmNlGAUgASgJEhMKC2Zvcm1hdF90eXBlGAYgASgJEhIKCnNvdXJjZV91cmwYByABKAkSGQoRaGFzX29sZF90ZXN0YW1lbnQYCCABKAgSGQoRaGFzX25ld190ZXN0YW1lbnQYCSABKAgSFQoNaGFzX2Fwb2NyeXBoYRgKIAEoCBIuCgpjcmVhdGVkX2F0GAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAwgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCKEAQoUR2V0QWxsVmVyc2lvblJlcXVlc3QSFQoIbGFuZ3VhZ2UYASABKAlIAIgBARITCgZzb3VyY2UYAiABKAlIAYgBARIYCgtmb3JtYXRfdHlwZRgDIAEoCUgCiAEBQgsKCV9sYW5ndWFnZUIJCgdfc291cmNlQg4KDF9mb3JtYXRfdHlwZSI8ChVHZXRBbGxWZXJzaW9uUmVzcG9uc2USIwoIdmVyc2lvbnMYASADKAsyES5iaWJsZS52MS5WZXJzaW9uIk4KFEdldE9uZVZlcnNpb25SZXF1ZXN0EhQKDHZlcnNpb25fY29kZRgBIAEoCRIQCghsYW5ndWFnZRgCIAEoCRIOCgZzb3VyY2UYAyABKAkiOwoVR2V0T25lVmVyc2lvblJlc3BvbnNlEiIKB3ZlcnNpb24YASABKAsyES5iaWJsZS52MS5WZXJzaW9uMoICCg5WZXJzaW9uU2VydmljZRJlCg1HZXRBbGxWZXJzaW9uEh4uYmlibGUudjEuR2V0QWxsVmVyc2lvblJlcXVlc3QaHy5iaWJsZS52MS5HZXRBbGxWZXJzaW9uUmVzcG9uc2UiE4LT5JMCDRILL3YxL3ZlcnNpb24SiAEKDUdldE9uZVZlcnNpb24SHi5iaWJsZS52MS5HZXRPbmVWZXJzaW9uUmVxdWVzdBofLmJpYmxlLnYxLkdldE9uZVZlcnNpb25SZXNwb25zZSI2gtPkkwIwEi4vdjEvdmVyc2lvbi97dmVyc2lvbl9jb2RlfS97bGFuZ3VhZ2V9L3tzb3VyY2V9QvoCCgxjb20uYmlibGUudjFCDFZlcnNpb25Qcm90b1ABWjZnaXRodWIuY29tL3YtYmlibGUvcHJvdG9idWYvcGtnL3Byb3RvL2JpYmxlL3YxO2JpYmxldjGiAgNCWFiqAghCaWJsZS5WMcoCCEJpYmxlXFYx4gIUQmlibGVcVjFcR1BCTWV0YWRhdGHqAglCaWJsZTo6VjGSQeEBEnAKGEJpYmxlIFZlcnNpb24gc2VydmVyIEFQSRIYQmlibGUgVmVyc2lvbiBzZXJ2ZXIgQVBJIjMKDkR1Y2t5TW9tbzIwMDEyEiFodHRwczovL2dpdGh1Yi5jb20vRHVja3lNb21vMjAwMTIyBTEuMC4wIgQvYXBpWlkKVwoGYmVhcmVyEk0IAhI4QXV0aGVudGljYXRpb24gdG9rZW4sIHByZWZpeGVkIGJ5IEJlYXJlcjogQmVhcmVyIDx0b2tlbj4aDUF1dGhvcml6YXRpb24gAmIMCgoKBmJlYXJlchIAYgZwcm90bzM", [file_google_api_annotations, file_google_protobuf_timestamp, file_protoc_gen_openapiv2_options_annotations]);

/**
 * @generated from message bible.v1.Version
 */
export type Version = Message<"bible.v1.Version"> & {
  /**
   * Version ID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Version code
   *
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * Version name
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Version language
   *
   * @generated from field: string language = 4;
   */
  language: string;

  /**
   * Version source
   *
   * @generated from field: string source = 5;
   */
  source: string;

  /**
   * Version format type
   *
   * @generated from field: string format_type = 6;
   */
  formatType: string;

  /**
   * Version source URL
   *
   * @generated from field: string source_url = 7;
   */
  sourceUrl: string;

  /**
   * Version has old testament
   *
   * @generated from field: bool has_old_testament = 8;
   */
  hasOldTestament: boolean;

  /**
   * Version has new testament
   *
   * @generated from field: bool has_new_testament = 9;
   */
  hasNewTestament: boolean;

  /**
   * Version has apocrypha
   *
   * @generated from field: bool has_apocrypha = 10;
   */
  hasApocrypha: boolean;

  /**
   * Version creation time
   * Stored in UTC and follows RFC 3339 format
   *
   * @generated from field: google.protobuf.Timestamp created_at = 11;
   */
  createdAt?: Timestamp;

  /**
   * Version last update time
   * Stored in UTC and follows RFC 3339 format
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 12;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message bible.v1.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema: GenMessage<Version> = /*@__PURE__*/
  messageDesc(file_bible_v1_version, 0);

/**
 * @generated from message bible.v1.GetAllVersionRequest
 */
export type GetAllVersionRequest = Message<"bible.v1.GetAllVersionRequest"> & {
  /**
   * Language filter (optional - indexed in Prisma)
   *
   * @generated from field: optional string language = 1;
   */
  language?: string;

  /**
   * Source filter (optional - indexed in Prisma)
   *
   * @generated from field: optional string source = 2;
   */
  source?: string;

  /**
   * Format type filter (optional - indexed in Prisma)
   *
   * @generated from field: optional string format_type = 3;
   */
  formatType?: string;
};

/**
 * Describes the message bible.v1.GetAllVersionRequest.
 * Use `create(GetAllVersionRequestSchema)` to create a new message.
 */
export const GetAllVersionRequestSchema: GenMessage<GetAllVersionRequest> = /*@__PURE__*/
  messageDesc(file_bible_v1_version, 1);

/**
 * @generated from message bible.v1.GetAllVersionResponse
 */
export type GetAllVersionResponse = Message<"bible.v1.GetAllVersionResponse"> & {
  /**
   * Version list
   *
   * @generated from field: repeated bible.v1.Version versions = 1;
   */
  versions: Version[];
};

/**
 * Describes the message bible.v1.GetAllVersionResponse.
 * Use `create(GetAllVersionResponseSchema)` to create a new message.
 */
export const GetAllVersionResponseSchema: GenMessage<GetAllVersionResponse> = /*@__PURE__*/
  messageDesc(file_bible_v1_version, 2);

/**
 * @generated from message bible.v1.GetOneVersionRequest
 */
export type GetOneVersionRequest = Message<"bible.v1.GetOneVersionRequest"> & {
  /**
   * Version code (required - part of unique constraint)
   *
   * @generated from field: string version_code = 1;
   */
  versionCode: string;

  /**
   * Language code (required - part of unique constraint)
   *
   * @generated from field: string language = 2;
   */
  language: string;

  /**
   * Source (required - part of unique constraint)
   *
   * @generated from field: string source = 3;
   */
  source: string;
};

/**
 * Describes the message bible.v1.GetOneVersionRequest.
 * Use `create(GetOneVersionRequestSchema)` to create a new message.
 */
export const GetOneVersionRequestSchema: GenMessage<GetOneVersionRequest> = /*@__PURE__*/
  messageDesc(file_bible_v1_version, 3);

/**
 * @generated from message bible.v1.GetOneVersionResponse
 */
export type GetOneVersionResponse = Message<"bible.v1.GetOneVersionResponse"> & {
  /**
   * Version object
   *
   * @generated from field: bible.v1.Version version = 1;
   */
  version?: Version;
};

/**
 * Describes the message bible.v1.GetOneVersionResponse.
 * Use `create(GetOneVersionResponseSchema)` to create a new message.
 */
export const GetOneVersionResponseSchema: GenMessage<GetOneVersionResponse> = /*@__PURE__*/
  messageDesc(file_bible_v1_version, 4);

/**
 * Version service definition
 *
 * @generated from service bible.v1.VersionService
 */
export const VersionService: GenService<{
  /**
   * Retrieve all versions
   *
   * @generated from rpc bible.v1.VersionService.GetAllVersion
   */
  getAllVersion: {
    methodKind: "unary";
    input: typeof GetAllVersionRequestSchema;
    output: typeof GetAllVersionResponseSchema;
  },
  /**
   * Retrieve one version by unique constraint
   *
   * @generated from rpc bible.v1.VersionService.GetOneVersion
   */
  getOneVersion: {
    methodKind: "unary";
    input: typeof GetOneVersionRequestSchema;
    output: typeof GetOneVersionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bible_v1_version, 0);

