services:
  swagger-service:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      # Ref: https://github.com/swagger-api/swagger-ui/issues/4915#issuecomment-475755863
      URLS: >
        [
          { url: 'docs/account/v1/account.swagger.json', name: 'Bible Account server API' },
          { url: 'docs/account/v1/auth.swagger.json', name: 'Bible Auth server API' },
          { url: 'docs/bible/v1/book.swagger.json', name: 'Bible Book server API' },
          { url: 'docs/bible/v1/version.swagger.json', name: 'Bible Version server API' },
        ]
    volumes:
      - ./openapi:/usr/share/nginx/html/docs/
    networks:
      - bible-net

networks:
  bible-net:
    driver: bridge
