// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: activity/v1/activity.proto

package activityv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnnotationKind int32

const (
	// Must be explicitly set - invalid default
	AnnotationKind_ANNOTATION_KIND_UNSPECIFIED AnnotationKind = 0
	// Highlight annotation
	AnnotationKind_ANNOTATION_KIND_HIGHLIGHT AnnotationKind = 1
	// Note annotation
	AnnotationKind_ANNOTATION_KIND_NOTE AnnotationKind = 2
)

// Enum value maps for AnnotationKind.
var (
	AnnotationKind_name = map[int32]string{
		0: "ANNOTATION_KIND_UNSPECIFIED",
		1: "ANNOTATION_KIND_HIGHLIGHT",
		2: "ANNOTATION_KIND_NOTE",
	}
	AnnotationKind_value = map[string]int32{
		"ANNOTATION_KIND_UNSPECIFIED": 0,
		"ANNOTATION_KIND_HIGHLIGHT":   1,
		"ANNOTATION_KIND_NOTE":        2,
	}
)

func (x AnnotationKind) Enum() *AnnotationKind {
	p := new(AnnotationKind)
	*p = x
	return p
}

func (x AnnotationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_v1_activity_proto_enumTypes[0].Descriptor()
}

func (AnnotationKind) Type() protoreflect.EnumType {
	return &file_activity_v1_activity_proto_enumTypes[0]
}

func (x AnnotationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationKind.Descriptor instead.
func (AnnotationKind) EnumDescriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{0}
}

type AnnotationTargetType int32

const (
	// Must be explicitly set - invalid default
	AnnotationTargetType_ANNOTATION_TARGET_TYPE_UNSPECIFIED AnnotationTargetType = 0
	// Verse target
	AnnotationTargetType_ANNOTATION_TARGET_TYPE_VERSE AnnotationTargetType = 1
	// Heading target
	AnnotationTargetType_ANNOTATION_TARGET_TYPE_HEADING AnnotationTargetType = 2
)

// Enum value maps for AnnotationTargetType.
var (
	AnnotationTargetType_name = map[int32]string{
		0: "ANNOTATION_TARGET_TYPE_UNSPECIFIED",
		1: "ANNOTATION_TARGET_TYPE_VERSE",
		2: "ANNOTATION_TARGET_TYPE_HEADING",
	}
	AnnotationTargetType_value = map[string]int32{
		"ANNOTATION_TARGET_TYPE_UNSPECIFIED": 0,
		"ANNOTATION_TARGET_TYPE_VERSE":       1,
		"ANNOTATION_TARGET_TYPE_HEADING":     2,
	}
)

func (x AnnotationTargetType) Enum() *AnnotationTargetType {
	p := new(AnnotationTargetType)
	*p = x
	return p
}

func (x AnnotationTargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnotationTargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_activity_v1_activity_proto_enumTypes[1].Descriptor()
}

func (AnnotationTargetType) Type() protoreflect.EnumType {
	return &file_activity_v1_activity_proto_enumTypes[1]
}

func (x AnnotationTargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnotationTargetType.Descriptor instead.
func (AnnotationTargetType) EnumDescriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{1}
}

type Annotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Annotation content
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Annotation kind
	Kind AnnotationKind `protobuf:"varint,3,opt,name=kind,proto3,enum=activity.v1.AnnotationKind" json:"kind,omitempty"`
	// Annotation color
	Color string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	// Annotation start offset. Starts from 0.
	StartOffset int32 `protobuf:"varint,5,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// Annotation end offset. Starts from 0.
	EndOffset int32 `protobuf:"varint,6,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	// Annotation creation time
	// Stored in UTC and follows RFC 3339 format
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Annotation last update time
	// Stored in UTC and follows RFC 3339 format
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Annotation target ID
	TargetId string `protobuf:"bytes,9,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Annotation target type
	TargetType AnnotationTargetType `protobuf:"varint,10,opt,name=target_type,json=targetType,proto3,enum=activity.v1.AnnotationTargetType" json:"target_type,omitempty"`
	// Account ID
	AccountId     string `protobuf:"bytes,11,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Annotation) Reset() {
	*x = Annotation{}
	mi := &file_activity_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Annotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Annotation) ProtoMessage() {}

func (x *Annotation) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Annotation.ProtoReflect.Descriptor instead.
func (*Annotation) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Annotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Annotation) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Annotation) GetKind() AnnotationKind {
	if x != nil {
		return x.Kind
	}
	return AnnotationKind_ANNOTATION_KIND_UNSPECIFIED
}

func (x *Annotation) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Annotation) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *Annotation) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *Annotation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Annotation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Annotation) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Annotation) GetTargetType() AnnotationTargetType {
	if x != nil {
		return x.TargetType
	}
	return AnnotationTargetType_ANNOTATION_TARGET_TYPE_UNSPECIFIED
}

func (x *Annotation) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAllAnnotationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID filter (required)
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Version code (required - part of unique constraint)
	VersionCode string `protobuf:"bytes,2,opt,name=version_code,json=versionCode,proto3" json:"version_code,omitempty"`
	// Language code (required - part of unique constraint)
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	// Source (required - part of unique constraint)
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Target ID filter (optional - filter by specific verse/heading)
	TargetId *string `protobuf:"bytes,5,opt,name=target_id,json=targetId,proto3,oneof" json:"target_id,omitempty"`
	// Target type filter (optional - filter by verse or heading)
	TargetType    *AnnotationTargetType `protobuf:"varint,6,opt,name=target_type,json=targetType,proto3,enum=activity.v1.AnnotationTargetType,oneof" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAnnotationsRequest) Reset() {
	*x = GetAllAnnotationsRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAnnotationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAnnotationsRequest) ProtoMessage() {}

func (x *GetAllAnnotationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAnnotationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAnnotationsRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllAnnotationsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAllAnnotationsRequest) GetVersionCode() string {
	if x != nil {
		return x.VersionCode
	}
	return ""
}

func (x *GetAllAnnotationsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetAllAnnotationsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetAllAnnotationsRequest) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *GetAllAnnotationsRequest) GetTargetType() AnnotationTargetType {
	if x != nil && x.TargetType != nil {
		return *x.TargetType
	}
	return AnnotationTargetType_ANNOTATION_TARGET_TYPE_UNSPECIFIED
}

type GetAllAnnotationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation list
	Annotations   []*Annotation `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAnnotationsResponse) Reset() {
	*x = GetAllAnnotationsResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAnnotationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAnnotationsResponse) ProtoMessage() {}

func (x *GetAllAnnotationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAnnotationsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAnnotationsResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllAnnotationsResponse) GetAnnotations() []*Annotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GetOneAnnotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation ID
	AnnotationId  string `protobuf:"bytes,1,opt,name=annotation_id,json=annotationId,proto3" json:"annotation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAnnotationRequest) Reset() {
	*x = GetOneAnnotationRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAnnotationRequest) ProtoMessage() {}

func (x *GetOneAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAnnotationRequest.ProtoReflect.Descriptor instead.
func (*GetOneAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneAnnotationRequest) GetAnnotationId() string {
	if x != nil {
		return x.AnnotationId
	}
	return ""
}

type GetOneAnnotationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation object
	Annotation    *Annotation `protobuf:"bytes,1,opt,name=annotation,proto3" json:"annotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneAnnotationResponse) Reset() {
	*x = GetOneAnnotationResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneAnnotationResponse) ProtoMessage() {}

func (x *GetOneAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneAnnotationResponse.ProtoReflect.Descriptor instead.
func (*GetOneAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneAnnotationResponse) GetAnnotation() *Annotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

type CreateAnnotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request body
	Body          *CreateAnnotationRequest_Body `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnotationRequest) Reset() {
	*x = CreateAnnotationRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnotationRequest) ProtoMessage() {}

func (x *CreateAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnotationRequest.ProtoReflect.Descriptor instead.
func (*CreateAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAnnotationRequest) GetBody() *CreateAnnotationRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type CreateAnnotationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created annotation object
	Annotation    *Annotation `protobuf:"bytes,1,opt,name=annotation,proto3" json:"annotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnotationResponse) Reset() {
	*x = CreateAnnotationResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnotationResponse) ProtoMessage() {}

func (x *CreateAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnotationResponse.ProtoReflect.Descriptor instead.
func (*CreateAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAnnotationResponse) GetAnnotation() *Annotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

type UpdateAnnotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation ID
	AnnotationId string `protobuf:"bytes,1,opt,name=annotation_id,json=annotationId,proto3" json:"annotation_id,omitempty"`
	// Request body
	Body          *UpdateAnnotationRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnotationRequest) Reset() {
	*x = UpdateAnnotationRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnotationRequest) ProtoMessage() {}

func (x *UpdateAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnotationRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAnnotationRequest) GetAnnotationId() string {
	if x != nil {
		return x.AnnotationId
	}
	return ""
}

func (x *UpdateAnnotationRequest) GetBody() *UpdateAnnotationRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type UpdateAnnotationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated annotation object
	Annotation    *Annotation `protobuf:"bytes,1,opt,name=annotation,proto3" json:"annotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnotationResponse) Reset() {
	*x = UpdateAnnotationResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnotationResponse) ProtoMessage() {}

func (x *UpdateAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnotationResponse.ProtoReflect.Descriptor instead.
func (*UpdateAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAnnotationResponse) GetAnnotation() *Annotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

type DeleteAnnotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation ID
	AnnotationId  string `protobuf:"bytes,1,opt,name=annotation_id,json=annotationId,proto3" json:"annotation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnotationRequest) Reset() {
	*x = DeleteAnnotationRequest{}
	mi := &file_activity_v1_activity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnotationRequest) ProtoMessage() {}

func (x *DeleteAnnotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnotationRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnnotationRequest) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAnnotationRequest) GetAnnotationId() string {
	if x != nil {
		return x.AnnotationId
	}
	return ""
}

type DeleteAnnotationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deleted annotation object
	Annotation    *Annotation `protobuf:"bytes,1,opt,name=annotation,proto3" json:"annotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnotationResponse) Reset() {
	*x = DeleteAnnotationResponse{}
	mi := &file_activity_v1_activity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnotationResponse) ProtoMessage() {}

func (x *DeleteAnnotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnotationResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnnotationResponse) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAnnotationResponse) GetAnnotation() *Annotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

// Request body message
type CreateAnnotationRequest_Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation content
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Annotation kind
	Kind AnnotationKind `protobuf:"varint,2,opt,name=kind,proto3,enum=activity.v1.AnnotationKind" json:"kind,omitempty"`
	// Annotation color
	Color string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	// Annotation start offset. Starts from 0.
	StartOffset int32 `protobuf:"varint,4,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	// Annotation end offset. Starts from 0.
	EndOffset int32 `protobuf:"varint,5,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	// Annotation target ID
	TargetId string `protobuf:"bytes,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Annotation target type
	TargetType    AnnotationTargetType `protobuf:"varint,7,opt,name=target_type,json=targetType,proto3,enum=activity.v1.AnnotationTargetType" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnotationRequest_Body) Reset() {
	*x = CreateAnnotationRequest_Body{}
	mi := &file_activity_v1_activity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnotationRequest_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnotationRequest_Body) ProtoMessage() {}

func (x *CreateAnnotationRequest_Body) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnotationRequest_Body.ProtoReflect.Descriptor instead.
func (*CreateAnnotationRequest_Body) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateAnnotationRequest_Body) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateAnnotationRequest_Body) GetKind() AnnotationKind {
	if x != nil {
		return x.Kind
	}
	return AnnotationKind_ANNOTATION_KIND_UNSPECIFIED
}

func (x *CreateAnnotationRequest_Body) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateAnnotationRequest_Body) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *CreateAnnotationRequest_Body) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *CreateAnnotationRequest_Body) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CreateAnnotationRequest_Body) GetTargetType() AnnotationTargetType {
	if x != nil {
		return x.TargetType
	}
	return AnnotationTargetType_ANNOTATION_TARGET_TYPE_UNSPECIFIED
}

// Request body message
type UpdateAnnotationRequest_Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Annotation content
	Content *string `protobuf:"bytes,1,opt,name=content,proto3,oneof" json:"content,omitempty"`
	// Annotation kind
	Kind *AnnotationKind `protobuf:"varint,2,opt,name=kind,proto3,enum=activity.v1.AnnotationKind,oneof" json:"kind,omitempty"`
	// Annotation color
	Color *string `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// Annotation start offset. Starts from 0.
	StartOffset *int32 `protobuf:"varint,4,opt,name=start_offset,json=startOffset,proto3,oneof" json:"start_offset,omitempty"`
	// Annotation end offset. Starts from 0.
	EndOffset     *int32 `protobuf:"varint,5,opt,name=end_offset,json=endOffset,proto3,oneof" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAnnotationRequest_Body) Reset() {
	*x = UpdateAnnotationRequest_Body{}
	mi := &file_activity_v1_activity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAnnotationRequest_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnnotationRequest_Body) ProtoMessage() {}

func (x *UpdateAnnotationRequest_Body) ProtoReflect() protoreflect.Message {
	mi := &file_activity_v1_activity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnnotationRequest_Body.ProtoReflect.Descriptor instead.
func (*UpdateAnnotationRequest_Body) Descriptor() ([]byte, []int) {
	return file_activity_v1_activity_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateAnnotationRequest_Body) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateAnnotationRequest_Body) GetKind() AnnotationKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return AnnotationKind_ANNOTATION_KIND_UNSPECIFIED
}

func (x *UpdateAnnotationRequest_Body) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateAnnotationRequest_Body) GetStartOffset() int32 {
	if x != nil && x.StartOffset != nil {
		return *x.StartOffset
	}
	return 0
}

func (x *UpdateAnnotationRequest_Body) GetEndOffset() int32 {
	if x != nil && x.EndOffset != nil {
		return *x.EndOffset
	}
	return 0
}

var File_activity_v1_activity_proto protoreflect.FileDescriptor

const file_activity_v1_activity_proto_rawDesc = "" +
	"\n" +
	"\x1aactivity/v1/activity.proto\x12\vactivity.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb5\x03\n" +
	"\n" +
	"Annotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.activity.v1.AnnotationKindR\x04kind\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12!\n" +
	"\fstart_offset\x18\x05 \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x06 \x01(\x05R\tendOffset\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\ttarget_id\x18\t \x01(\tR\btargetId\x12B\n" +
	"\vtarget_type\x18\n" +
	" \x01(\x0e2!.activity.v1.AnnotationTargetTypeR\n" +
	"targetType\x12\x1d\n" +
	"\n" +
	"account_id\x18\v \x01(\tR\taccountId\"\x99\x02\n" +
	"\x18GetAllAnnotationsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fversion_code\x18\x02 \x01(\tR\vversionCode\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12 \n" +
	"\ttarget_id\x18\x05 \x01(\tH\x00R\btargetId\x88\x01\x01\x12G\n" +
	"\vtarget_type\x18\x06 \x01(\x0e2!.activity.v1.AnnotationTargetTypeH\x01R\n" +
	"targetType\x88\x01\x01B\f\n" +
	"\n" +
	"_target_idB\x0e\n" +
	"\f_target_type\"V\n" +
	"\x19GetAllAnnotationsResponse\x129\n" +
	"\vannotations\x18\x01 \x03(\v2\x17.activity.v1.AnnotationR\vannotations\">\n" +
	"\x17GetOneAnnotationRequest\x12#\n" +
	"\rannotation_id\x18\x01 \x01(\tR\fannotationId\"S\n" +
	"\x18GetOneAnnotationResponse\x127\n" +
	"\n" +
	"annotation\x18\x01 \x01(\v2\x17.activity.v1.AnnotationR\n" +
	"annotation\"\xe5\x02\n" +
	"\x17CreateAnnotationRequest\x12=\n" +
	"\x04body\x18\x01 \x01(\v2).activity.v1.CreateAnnotationRequest.BodyR\x04body\x1a\x8a\x02\n" +
	"\x04Body\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12/\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.activity.v1.AnnotationKindR\x04kind\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12!\n" +
	"\fstart_offset\x18\x04 \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x05 \x01(\x05R\tendOffset\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\tR\btargetId\x12B\n" +
	"\vtarget_type\x18\a \x01(\x0e2!.activity.v1.AnnotationTargetTypeR\n" +
	"targetType\"S\n" +
	"\x18CreateAnnotationResponse\x127\n" +
	"\n" +
	"annotation\x18\x01 \x01(\v2\x17.activity.v1.AnnotationR\n" +
	"annotation\"\x81\x03\n" +
	"\x17UpdateAnnotationRequest\x12#\n" +
	"\rannotation_id\x18\x01 \x01(\tR\fannotationId\x12=\n" +
	"\x04body\x18\x02 \x01(\v2).activity.v1.UpdateAnnotationRequest.BodyR\x04body\x1a\x81\x02\n" +
	"\x04Body\x12\x1d\n" +
	"\acontent\x18\x01 \x01(\tH\x00R\acontent\x88\x01\x01\x124\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1b.activity.v1.AnnotationKindH\x01R\x04kind\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x02R\x05color\x88\x01\x01\x12&\n" +
	"\fstart_offset\x18\x04 \x01(\x05H\x03R\vstartOffset\x88\x01\x01\x12\"\n" +
	"\n" +
	"end_offset\x18\x05 \x01(\x05H\x04R\tendOffset\x88\x01\x01B\n" +
	"\n" +
	"\b_contentB\a\n" +
	"\x05_kindB\b\n" +
	"\x06_colorB\x0f\n" +
	"\r_start_offsetB\r\n" +
	"\v_end_offset\"S\n" +
	"\x18UpdateAnnotationResponse\x127\n" +
	"\n" +
	"annotation\x18\x01 \x01(\v2\x17.activity.v1.AnnotationR\n" +
	"annotation\">\n" +
	"\x17DeleteAnnotationRequest\x12#\n" +
	"\rannotation_id\x18\x01 \x01(\tR\fannotationId\"S\n" +
	"\x18DeleteAnnotationResponse\x127\n" +
	"\n" +
	"annotation\x18\x01 \x01(\v2\x17.activity.v1.AnnotationR\n" +
	"annotation*j\n" +
	"\x0eAnnotationKind\x12\x1f\n" +
	"\x1bANNOTATION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ANNOTATION_KIND_HIGHLIGHT\x10\x01\x12\x18\n" +
	"\x14ANNOTATION_KIND_NOTE\x10\x02*\x84\x01\n" +
	"\x14AnnotationTargetType\x12&\n" +
	"\"ANNOTATION_TARGET_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cANNOTATION_TARGET_TYPE_VERSE\x10\x01\x12\"\n" +
	"\x1eANNOTATION_TARGET_TYPE_HEADING\x10\x022\xb0\x05\n" +
	"\x0fActivityService\x12z\n" +
	"\x11GetAllAnnotations\x12%.activity.v1.GetAllAnnotationsRequest\x1a&.activity.v1.GetAllAnnotationsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/annotation\x12\x87\x01\n" +
	"\x10GetOneAnnotation\x12$.activity.v1.GetOneAnnotationRequest\x1a%.activity.v1.GetOneAnnotationResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/annotation/{annotation_id}\x12}\n" +
	"\x10CreateAnnotation\x12$.activity.v1.CreateAnnotationRequest\x1a%.activity.v1.CreateAnnotationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x04body\"\x0e/v1/annotation\x12\x8d\x01\n" +
	"\x10UpdateAnnotation\x12$.activity.v1.UpdateAnnotationRequest\x1a%.activity.v1.UpdateAnnotationResponse\",\x82\xd3\xe4\x93\x02&:\x04body\x1a\x1e/v1/annotation/{annotation_id}\x12\x87\x01\n" +
	"\x10DeleteAnnotation\x12$.activity.v1.DeleteAnnotationRequest\x1a%.activity.v1.DeleteAnnotationResponse\"&\x82\xd3\xe4\x93\x02 *\x1e/v1/annotation/{annotation_id}B\x92\x03\x92A\xe3\x01\x12r\n" +
	"\x19Bible Activity server API\x12\x19Bible Activity server API\"3\n" +
	"\x0eDuckyMomo20012\x12!https://github.com/DuckyMomo200122\x051.0.0\"\x04/apiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\n" +
	"\x0fcom.activity.v1B\rActivityProtoP\x01Z<github.com/v-bible/protobuf/pkg/proto/activity/v1;activityv1\xa2\x02\x03AXX\xaa\x02\vActivity.V1\xca\x02\vActivity\\V1\xe2\x02\x17Activity\\V1\\GPBMetadata\xea\x02\fActivity::V1b\x06proto3"

var (
	file_activity_v1_activity_proto_rawDescOnce sync.Once
	file_activity_v1_activity_proto_rawDescData []byte
)

func file_activity_v1_activity_proto_rawDescGZIP() []byte {
	file_activity_v1_activity_proto_rawDescOnce.Do(func() {
		file_activity_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_v1_activity_proto_rawDesc), len(file_activity_v1_activity_proto_rawDesc)))
	})
	return file_activity_v1_activity_proto_rawDescData
}

var file_activity_v1_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_activity_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_activity_v1_activity_proto_goTypes = []any{
	(AnnotationKind)(0),                  // 0: activity.v1.AnnotationKind
	(AnnotationTargetType)(0),            // 1: activity.v1.AnnotationTargetType
	(*Annotation)(nil),                   // 2: activity.v1.Annotation
	(*GetAllAnnotationsRequest)(nil),     // 3: activity.v1.GetAllAnnotationsRequest
	(*GetAllAnnotationsResponse)(nil),    // 4: activity.v1.GetAllAnnotationsResponse
	(*GetOneAnnotationRequest)(nil),      // 5: activity.v1.GetOneAnnotationRequest
	(*GetOneAnnotationResponse)(nil),     // 6: activity.v1.GetOneAnnotationResponse
	(*CreateAnnotationRequest)(nil),      // 7: activity.v1.CreateAnnotationRequest
	(*CreateAnnotationResponse)(nil),     // 8: activity.v1.CreateAnnotationResponse
	(*UpdateAnnotationRequest)(nil),      // 9: activity.v1.UpdateAnnotationRequest
	(*UpdateAnnotationResponse)(nil),     // 10: activity.v1.UpdateAnnotationResponse
	(*DeleteAnnotationRequest)(nil),      // 11: activity.v1.DeleteAnnotationRequest
	(*DeleteAnnotationResponse)(nil),     // 12: activity.v1.DeleteAnnotationResponse
	(*CreateAnnotationRequest_Body)(nil), // 13: activity.v1.CreateAnnotationRequest.Body
	(*UpdateAnnotationRequest_Body)(nil), // 14: activity.v1.UpdateAnnotationRequest.Body
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_activity_v1_activity_proto_depIdxs = []int32{
	0,  // 0: activity.v1.Annotation.kind:type_name -> activity.v1.AnnotationKind
	15, // 1: activity.v1.Annotation.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: activity.v1.Annotation.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: activity.v1.Annotation.target_type:type_name -> activity.v1.AnnotationTargetType
	1,  // 4: activity.v1.GetAllAnnotationsRequest.target_type:type_name -> activity.v1.AnnotationTargetType
	2,  // 5: activity.v1.GetAllAnnotationsResponse.annotations:type_name -> activity.v1.Annotation
	2,  // 6: activity.v1.GetOneAnnotationResponse.annotation:type_name -> activity.v1.Annotation
	13, // 7: activity.v1.CreateAnnotationRequest.body:type_name -> activity.v1.CreateAnnotationRequest.Body
	2,  // 8: activity.v1.CreateAnnotationResponse.annotation:type_name -> activity.v1.Annotation
	14, // 9: activity.v1.UpdateAnnotationRequest.body:type_name -> activity.v1.UpdateAnnotationRequest.Body
	2,  // 10: activity.v1.UpdateAnnotationResponse.annotation:type_name -> activity.v1.Annotation
	2,  // 11: activity.v1.DeleteAnnotationResponse.annotation:type_name -> activity.v1.Annotation
	0,  // 12: activity.v1.CreateAnnotationRequest.Body.kind:type_name -> activity.v1.AnnotationKind
	1,  // 13: activity.v1.CreateAnnotationRequest.Body.target_type:type_name -> activity.v1.AnnotationTargetType
	0,  // 14: activity.v1.UpdateAnnotationRequest.Body.kind:type_name -> activity.v1.AnnotationKind
	3,  // 15: activity.v1.ActivityService.GetAllAnnotations:input_type -> activity.v1.GetAllAnnotationsRequest
	5,  // 16: activity.v1.ActivityService.GetOneAnnotation:input_type -> activity.v1.GetOneAnnotationRequest
	7,  // 17: activity.v1.ActivityService.CreateAnnotation:input_type -> activity.v1.CreateAnnotationRequest
	9,  // 18: activity.v1.ActivityService.UpdateAnnotation:input_type -> activity.v1.UpdateAnnotationRequest
	11, // 19: activity.v1.ActivityService.DeleteAnnotation:input_type -> activity.v1.DeleteAnnotationRequest
	4,  // 20: activity.v1.ActivityService.GetAllAnnotations:output_type -> activity.v1.GetAllAnnotationsResponse
	6,  // 21: activity.v1.ActivityService.GetOneAnnotation:output_type -> activity.v1.GetOneAnnotationResponse
	8,  // 22: activity.v1.ActivityService.CreateAnnotation:output_type -> activity.v1.CreateAnnotationResponse
	10, // 23: activity.v1.ActivityService.UpdateAnnotation:output_type -> activity.v1.UpdateAnnotationResponse
	12, // 24: activity.v1.ActivityService.DeleteAnnotation:output_type -> activity.v1.DeleteAnnotationResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_activity_v1_activity_proto_init() }
func file_activity_v1_activity_proto_init() {
	if File_activity_v1_activity_proto != nil {
		return
	}
	file_activity_v1_activity_proto_msgTypes[1].OneofWrappers = []any{}
	file_activity_v1_activity_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_v1_activity_proto_rawDesc), len(file_activity_v1_activity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_v1_activity_proto_goTypes,
		DependencyIndexes: file_activity_v1_activity_proto_depIdxs,
		EnumInfos:         file_activity_v1_activity_proto_enumTypes,
		MessageInfos:      file_activity_v1_activity_proto_msgTypes,
	}.Build()
	File_activity_v1_activity_proto = out.File
	file_activity_v1_activity_proto_goTypes = nil
	file_activity_v1_activity_proto_depIdxs = nil
}
