// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: account/v1/account.proto

package accountv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Account email
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// Account first name
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Account last name
	LastName string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Account creation time
	// Stored in UTC and follows RFC 3339 format
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Account) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AccountSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Account session start time
	// Stored in UTC and follows RFC 3339 format
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	// Account session last access time
	// Stored in UTC and follows RFC 3339 format
	LastAccess *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_access,json=lastAccess,proto3" json:"last_access,omitempty"`
	// Account session IP address
	IpAddress     string `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSession) Reset() {
	*x = AccountSession{}
	mi := &file_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSession) ProtoMessage() {}

func (x *AccountSession) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSession.ProtoReflect.Descriptor instead.
func (*AccountSession) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountSession) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountSession) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AccountSession) GetLastAccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAccess
	}
	return nil
}

func (x *AccountSession) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type GetAccountByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdRequest) Reset() {
	*x = GetAccountByIdRequest{}
	mi := &file_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdRequest) ProtoMessage() {}

func (x *GetAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountByIdResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account object
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdResponse) Reset() {
	*x = GetAccountByIdResponse{}
	mi := &file_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdResponse) ProtoMessage() {}

func (x *GetAccountByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByIdResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountByIdResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSessionRequest) Reset() {
	*x = GetAccountSessionRequest{}
	mi := &file_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSessionRequest) ProtoMessage() {}

func (x *GetAccountSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSessionRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSessionRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountSessionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account session object
	Session       []*AccountSession `protobuf:"bytes,1,rep,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSessionResponse) Reset() {
	*x = GetAccountSessionResponse{}
	mi := &file_account_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSessionResponse) ProtoMessage() {}

func (x *GetAccountSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSessionResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSessionResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountSessionResponse) GetSession() []*AccountSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type UpdateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Request body
	Body          *UpdateAccountRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_account_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateAccountRequest) GetBody() *UpdateAccountRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type UpdateAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account object
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_account_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type UpdateAccountPasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Request body
	Body          *UpdateAccountPasswordRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountPasswordRequest) Reset() {
	*x = UpdateAccountPasswordRequest{}
	mi := &file_account_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountPasswordRequest) ProtoMessage() {}

func (x *UpdateAccountPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountPasswordRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountPasswordRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateAccountPasswordRequest) GetBody() *UpdateAccountPasswordRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type UpdateAccountPasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account object
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountPasswordResponse) Reset() {
	*x = UpdateAccountPasswordResponse{}
	mi := &file_account_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountPasswordResponse) ProtoMessage() {}

func (x *UpdateAccountPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountPasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountPasswordResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAccountPasswordResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account ID
	AccountId     string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_account_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account object
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_account_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// Request body message
type UpdateAccountRequest_Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account first name
	FirstName *string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	// Account last name
	LastName      *string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest_Body) Reset() {
	*x = UpdateAccountRequest_Body{}
	mi := &file_account_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest_Body) ProtoMessage() {}

func (x *UpdateAccountRequest_Body) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest_Body.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest_Body) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateAccountRequest_Body) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateAccountRequest_Body) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

// Request body message
type UpdateAccountPasswordRequest_Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account password
	Password      string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountPasswordRequest_Body) Reset() {
	*x = UpdateAccountPasswordRequest_Body{}
	mi := &file_account_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountPasswordRequest_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountPasswordRequest_Body) ProtoMessage() {}

func (x *UpdateAccountPasswordRequest_Body) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountPasswordRequest_Body.ProtoReflect.Descriptor instead.
func (*UpdateAccountPasswordRequest_Body) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateAccountPasswordRequest_Body) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_account_v1_account_proto protoreflect.FileDescriptor

const file_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x18account/v1/account.proto\x12\n" +
	"account.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb5\x01\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbd\x01\n" +
	"\x0eAccountSession\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12;\n" +
	"\vlast_access\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastAccess\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\"6\n" +
	"\x15GetAccountByIdRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"G\n" +
	"\x16GetAccountByIdResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"9\n" +
	"\x18GetAccountSessionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"Q\n" +
	"\x19GetAccountSessionResponse\x124\n" +
	"\asession\x18\x01 \x03(\v2\x1a.account.v1.AccountSessionR\asession\"\xdb\x01\n" +
	"\x14UpdateAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x129\n" +
	"\x04body\x18\x02 \x01(\v2%.account.v1.UpdateAccountRequest.BodyR\x04body\x1ai\n" +
	"\x04Body\x12\"\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x02 \x01(\tH\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"F\n" +
	"\x15UpdateAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"\xa4\x01\n" +
	"\x1cUpdateAccountPasswordRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12A\n" +
	"\x04body\x18\x02 \x01(\v2-.account.v1.UpdateAccountPasswordRequest.BodyR\x04body\x1a\"\n" +
	"\x04Body\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"N\n" +
	"\x1dUpdateAccountPasswordResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"5\n" +
	"\x14DeleteAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"F\n" +
	"\x15DeleteAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount2\xae\x05\n" +
	"\x0eAccountService\x12y\n" +
	"\x0eGetAccountById\x12!.account.v1.GetAccountByIdRequest\x1a\".account.v1.GetAccountByIdResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/account/{account_id}\x12\x8a\x01\n" +
	"\x11GetAccountSession\x12$.account.v1.GetAccountSessionRequest\x1a%.account.v1.GetAccountSessionResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/account/{account_id}/session\x12|\n" +
	"\rUpdateAccount\x12 .account.v1.UpdateAccountRequest\x1a!.account.v1.UpdateAccountResponse\"&\x82\xd3\xe4\x93\x02 :\x04body\x1a\x18/v1/account/{account_id}\x12\x9d\x01\n" +
	"\x15UpdateAccountPassword\x12(.account.v1.UpdateAccountPasswordRequest\x1a).account.v1.UpdateAccountPasswordResponse\"/\x82\xd3\xe4\x93\x02):\x04body\x1a!/v1/account/{account_id}/password\x12v\n" +
	"\rDeleteAccount\x12 .account.v1.DeleteAccountRequest\x1a!.account.v1.DeleteAccountResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/account/{account_id}B\x88\x03\x92A\xe1\x01\x12p\n" +
	"\x18Bible Account server API\x12\x18Bible Account server API\"3\n" +
	"\x0eDuckyMomo20012\x12!https://github.com/DuckyMomo200122\x051.0.0\"\x04/apiZY\n" +
	"W\n" +
	"\x06bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer <token>\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\n" +
	"\x0ecom.account.v1B\fAccountProtoP\x01Z:github.com/v-bible/protobuf/pkg/proto/account/v1;accountv1\xa2\x02\x03AXX\xaa\x02\n" +
	"Account.V1\xca\x02\n" +
	"Account\\V1\xe2\x02\x16Account\\V1\\GPBMetadata\xea\x02\vAccount::V1b\x06proto3"

var (
	file_account_v1_account_proto_rawDescOnce sync.Once
	file_account_v1_account_proto_rawDescData []byte
)

func file_account_v1_account_proto_rawDescGZIP() []byte {
	file_account_v1_account_proto_rawDescOnce.Do(func() {
		file_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)))
	})
	return file_account_v1_account_proto_rawDescData
}

var file_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_account_v1_account_proto_goTypes = []any{
	(*Account)(nil),                           // 0: account.v1.Account
	(*AccountSession)(nil),                    // 1: account.v1.AccountSession
	(*GetAccountByIdRequest)(nil),             // 2: account.v1.GetAccountByIdRequest
	(*GetAccountByIdResponse)(nil),            // 3: account.v1.GetAccountByIdResponse
	(*GetAccountSessionRequest)(nil),          // 4: account.v1.GetAccountSessionRequest
	(*GetAccountSessionResponse)(nil),         // 5: account.v1.GetAccountSessionResponse
	(*UpdateAccountRequest)(nil),              // 6: account.v1.UpdateAccountRequest
	(*UpdateAccountResponse)(nil),             // 7: account.v1.UpdateAccountResponse
	(*UpdateAccountPasswordRequest)(nil),      // 8: account.v1.UpdateAccountPasswordRequest
	(*UpdateAccountPasswordResponse)(nil),     // 9: account.v1.UpdateAccountPasswordResponse
	(*DeleteAccountRequest)(nil),              // 10: account.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),             // 11: account.v1.DeleteAccountResponse
	(*UpdateAccountRequest_Body)(nil),         // 12: account.v1.UpdateAccountRequest.Body
	(*UpdateAccountPasswordRequest_Body)(nil), // 13: account.v1.UpdateAccountPasswordRequest.Body
	(*timestamppb.Timestamp)(nil),             // 14: google.protobuf.Timestamp
}
var file_account_v1_account_proto_depIdxs = []int32{
	14, // 0: account.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: account.v1.AccountSession.start:type_name -> google.protobuf.Timestamp
	14, // 2: account.v1.AccountSession.last_access:type_name -> google.protobuf.Timestamp
	0,  // 3: account.v1.GetAccountByIdResponse.account:type_name -> account.v1.Account
	1,  // 4: account.v1.GetAccountSessionResponse.session:type_name -> account.v1.AccountSession
	12, // 5: account.v1.UpdateAccountRequest.body:type_name -> account.v1.UpdateAccountRequest.Body
	0,  // 6: account.v1.UpdateAccountResponse.account:type_name -> account.v1.Account
	13, // 7: account.v1.UpdateAccountPasswordRequest.body:type_name -> account.v1.UpdateAccountPasswordRequest.Body
	0,  // 8: account.v1.UpdateAccountPasswordResponse.account:type_name -> account.v1.Account
	0,  // 9: account.v1.DeleteAccountResponse.account:type_name -> account.v1.Account
	2,  // 10: account.v1.AccountService.GetAccountById:input_type -> account.v1.GetAccountByIdRequest
	4,  // 11: account.v1.AccountService.GetAccountSession:input_type -> account.v1.GetAccountSessionRequest
	6,  // 12: account.v1.AccountService.UpdateAccount:input_type -> account.v1.UpdateAccountRequest
	8,  // 13: account.v1.AccountService.UpdateAccountPassword:input_type -> account.v1.UpdateAccountPasswordRequest
	10, // 14: account.v1.AccountService.DeleteAccount:input_type -> account.v1.DeleteAccountRequest
	3,  // 15: account.v1.AccountService.GetAccountById:output_type -> account.v1.GetAccountByIdResponse
	5,  // 16: account.v1.AccountService.GetAccountSession:output_type -> account.v1.GetAccountSessionResponse
	7,  // 17: account.v1.AccountService.UpdateAccount:output_type -> account.v1.UpdateAccountResponse
	9,  // 18: account.v1.AccountService.UpdateAccountPassword:output_type -> account.v1.UpdateAccountPasswordResponse
	11, // 19: account.v1.AccountService.DeleteAccount:output_type -> account.v1.DeleteAccountResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_account_v1_account_proto_init() }
func file_account_v1_account_proto_init() {
	if File_account_v1_account_proto != nil {
		return
	}
	file_account_v1_account_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_account_proto_goTypes,
		DependencyIndexes: file_account_v1_account_proto_depIdxs,
		MessageInfos:      file_account_v1_account_proto_msgTypes,
	}.Build()
	File_account_v1_account_proto = out.File
	file_account_v1_account_proto_goTypes = nil
	file_account_v1_account_proto_depIdxs = nil
}
