// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: bible/v1/version.proto

package biblev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VersionService_GetAllVersion_FullMethodName = "/bible.v1.VersionService/GetAllVersion"
	VersionService_GetOneVersion_FullMethodName = "/bible.v1.VersionService/GetOneVersion"
)

// VersionServiceClient is the client API for VersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Version service definition
type VersionServiceClient interface {
	// Retrieve all versions
	GetAllVersion(ctx context.Context, in *GetAllVersionRequest, opts ...grpc.CallOption) (*GetAllVersionResponse, error)
	// Retrieve one version by unique constraint
	GetOneVersion(ctx context.Context, in *GetOneVersionRequest, opts ...grpc.CallOption) (*GetOneVersionResponse, error)
}

type versionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVersionServiceClient(cc grpc.ClientConnInterface) VersionServiceClient {
	return &versionServiceClient{cc}
}

func (c *versionServiceClient) GetAllVersion(ctx context.Context, in *GetAllVersionRequest, opts ...grpc.CallOption) (*GetAllVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllVersionResponse)
	err := c.cc.Invoke(ctx, VersionService_GetAllVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *versionServiceClient) GetOneVersion(ctx context.Context, in *GetOneVersionRequest, opts ...grpc.CallOption) (*GetOneVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOneVersionResponse)
	err := c.cc.Invoke(ctx, VersionService_GetOneVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VersionServiceServer is the server API for VersionService service.
// All implementations must embed UnimplementedVersionServiceServer
// for forward compatibility.
//
// Version service definition
type VersionServiceServer interface {
	// Retrieve all versions
	GetAllVersion(context.Context, *GetAllVersionRequest) (*GetAllVersionResponse, error)
	// Retrieve one version by unique constraint
	GetOneVersion(context.Context, *GetOneVersionRequest) (*GetOneVersionResponse, error)
	mustEmbedUnimplementedVersionServiceServer()
}

// UnimplementedVersionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVersionServiceServer struct{}

func (UnimplementedVersionServiceServer) GetAllVersion(context.Context, *GetAllVersionRequest) (*GetAllVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllVersion not implemented")
}
func (UnimplementedVersionServiceServer) GetOneVersion(context.Context, *GetOneVersionRequest) (*GetOneVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneVersion not implemented")
}
func (UnimplementedVersionServiceServer) mustEmbedUnimplementedVersionServiceServer() {}
func (UnimplementedVersionServiceServer) testEmbeddedByValue()                        {}

// UnsafeVersionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VersionServiceServer will
// result in compilation errors.
type UnsafeVersionServiceServer interface {
	mustEmbedUnimplementedVersionServiceServer()
}

func RegisterVersionServiceServer(s grpc.ServiceRegistrar, srv VersionServiceServer) {
	// If the following call pancis, it indicates UnimplementedVersionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VersionService_ServiceDesc, srv)
}

func _VersionService_GetAllVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).GetAllVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_GetAllVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).GetAllVersion(ctx, req.(*GetAllVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VersionService_GetOneVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).GetOneVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VersionService_GetOneVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).GetOneVersion(ctx, req.(*GetOneVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VersionService_ServiceDesc is the grpc.ServiceDesc for VersionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VersionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bible.v1.VersionService",
	HandlerType: (*VersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllVersion",
			Handler:    _VersionService_GetAllVersion_Handler,
		},
		{
			MethodName: "GetOneVersion",
			Handler:    _VersionService_GetOneVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bible/v1/version.proto",
}
